

name: Scheduled Data Taking

on:
  push:
    branches:
      - dev
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  cron:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      # Runs a single command using the runners shell
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run workflow
        run: python -c "import selenium; import os; print(os.system('ls -l'))"
=======
>>>>>>> 7a6a857929766f56301196042efbc499144b85ff

    - uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: Run Main
      env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }} 
          MONGO_CLIENT_ID: ${{ secrets.MONGO_CLIENT }}
      run: python ./production/main.py --mode op --mongo_client ${{ secrets.MONGO_CLIENT }}
