

name: Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    
    - name: Authentification
      run: curl -u s3flsago:Ingwer!2 "https://api.github.com/repos/user/repo/issues?state=closed"

    - name: Run tests
      run: python -m unittest
